/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.trabalho_programacao;

import Classes.Projeto;
import Classes.Repositorio;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vasco Cardoso
 */
public class Painel_verProjetos extends javax.swing.JPanel {

    DefaultTableModel tabela = new DefaultTableModel();
    
    
    /**
     * Creates new form Painel_verProjetos
     */
    public Painel_verProjetos() {
        initComponents();
        
        Object colunas[] = {"Nome", "Cliente", "Preço/Hora", "Dono"};
        tabela.setColumnIdentifiers(colunas);
        this.tabelaProjetos.setModel(tabela);
        
        this.popularTabela();
        
        
    }
    
    public void popularTabela(){
        Object obj[] = new Object[4];
        String username = Repositorio.getInstance().getUser().getUsername();
        for(Projeto p : Repositorio.getInstance().getProjetosByUsername(username) ){
            obj[0] = p.getNome();
            obj[1] = p.getNomeCliente();
            String preco = String.format("%,.2f", p.getPrecoHora());
            obj[2] = preco;
            obj[3] = p.getDono();
            
            tabela.addRow(obj);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        voltarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProjetos = new javax.swing.JTable();
        adicionarButton = new javax.swing.JButton();
        removerButton = new javax.swing.JButton();
        relatorioButton = new javax.swing.JButton();

        voltarButton.setText("Voltar");
        voltarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarButtonMouseClicked(evt);
            }
        });
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema de rastreio de tempo em tarefas");
        jLabel1.setAutoscrolls(true);
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(152, 55));
        jLabel1.setMinimumSize(new java.awt.Dimension(152, 55));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(152, 25));

        tabelaProjetos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaProjetos);

        adicionarButton.setText("Adicionar Usuario");
        adicionarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adicionarButtonMouseClicked(evt);
            }
        });

        removerButton.setText("Eliminar Usuario");
        removerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removerButtonMouseClicked(evt);
            }
        });

        relatorioButton.setText("Relatório");
        relatorioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                relatorioButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(relatorioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(removerButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(adicionarButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(180, 180, 180)
                                .addComponent(voltarButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adicionarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 16, Short.MAX_VALUE)
                        .addComponent(voltarButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(relatorioButton)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void voltarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarButtonMouseClicked
        Painel_menuUtilizador pInicial = new Painel_menuUtilizador ();
        JFrame.getFrame().AvancarParaPainel(pInicial, this.jPanel1);
        JFrame.getFrame().setSize(600, 400);
        JFrame.getFrame().setLocationRelativeTo(null);
    }//GEN-LAST:event_voltarButtonMouseClicked

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void removerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removerButtonMouseClicked
        
        int row = this.tabelaProjetos.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(null, "Escolha um projeto");
            return;
        }
        
        String projeto = (String) this.tabelaProjetos.getValueAt(row, 0);
        
        Projeto proj = Repositorio.getInstance().getProjetoByName(projeto);
        
        if(proj.getConvidados().isEmpty()){
            JOptionPane.showMessageDialog(null, "O projeto não tem utilizadores convidados");
            return;
        }
        
        if(proj.getDono().equals(Repositorio.getInstance().getUser().getUsername())){
            Painel_retirarUtilizador pInicial = new Painel_retirarUtilizador(proj);  
            JFrame.getFrame().AvancarParaPainel(pInicial, this.jPanel1);
            JFrame.getFrame().setSize(450, 400);
            JFrame.getFrame().setLocationRelativeTo(null);
        }else{
            JOptionPane.showMessageDialog(null, "Não tem permissões para remover convidados deste projeto!");
        }
        
                
        
    }//GEN-LAST:event_removerButtonMouseClicked

    private void adicionarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adicionarButtonMouseClicked
        
        int row = this.tabelaProjetos.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(null, "Escolha um projeto");
            return;
        }
        
        String projeto = (String) this.tabelaProjetos.getValueAt(row, 0);
        Projeto proj = Repositorio.getInstance().getProjetoByName(projeto);
        
        if(proj.getDono().equals(Repositorio.getInstance().getUser().getUsername())){
            Painel_addUtilizador pInicial = new Painel_addUtilizador(proj);  
            JFrame.getFrame().AvancarParaPainel(pInicial, this.jPanel1);
            JFrame.getFrame().setSize(450, 400);
            JFrame.getFrame().setLocationRelativeTo(null);
        }else{
            JOptionPane.showMessageDialog(null, "Não tem permissões para adicionar convidados a este projeto!");
        }
            
        
       
        
        
        
        
    }//GEN-LAST:event_adicionarButtonMouseClicked

    private void relatorioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_relatorioButtonMouseClicked
        
        int row = this.tabelaProjetos.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(null, "Escolha um projeto");
            return;
        }
        
        String projeto = (String) this.tabelaProjetos.getValueAt(row, 0);
        Projeto proj = Repositorio.getInstance().getProjetoByName(projeto);
        
        Painel_relatorioMensalProjeto pInicial = new Painel_relatorioMensalProjeto(proj);  
        JFrame.getFrame().AvancarParaPainel(pInicial, this.jPanel1);
        JFrame.getFrame().setSize(800, 500);
        JFrame.getFrame().setLocationRelativeTo(null);
        
    }//GEN-LAST:event_relatorioButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton relatorioButton;
    private javax.swing.JButton removerButton;
    private javax.swing.JTable tabelaProjetos;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
