/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.trabalho_programacao;

import Classes.Projeto;
import Classes.Repositorio;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vasco Cardoso
 */
public class Painel_verConvites extends javax.swing.JPanel {

    
    DefaultTableModel tabela = new DefaultTableModel();
    
    
    /**
     * Creates new form Painel_verConvites
     */
    public Painel_verConvites() {
        initComponents();
        
        Object colunas[] = {"Nome", "Cliente", "Preço/Hora", "Dono"};
        tabela.setColumnIdentifiers(colunas);
        this.conviteTabela.setModel(tabela);
        
        popularTabela();
        
    }
    
    
    public void popularTabela(){
        Object obj[] = new Object[4];
        for(String convite : Repositorio.getInstance().getUser().getConvites()){
            Projeto p = Repositorio.getInstance().getProjetoByName(convite);
            
            obj[0] = p.getNome();
            obj[1] = p.getNomeCliente();
            obj[2] = p.getPrecoHora();
            obj[2] = p.getDono();

            tabela.addRow(obj);
                
            
        }
        
        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        voltarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        conviteTabela = new javax.swing.JTable();
        rejeitarButton = new javax.swing.JButton();
        aceitarButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema de rastreio de tempo em tarefas");
        jLabel1.setAutoscrolls(true);
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(152, 55));
        jLabel1.setMinimumSize(new java.awt.Dimension(152, 55));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(152, 25));

        voltarButton.setText("Voltar");
        voltarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarButtonMouseClicked(evt);
            }
        });
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        conviteTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(conviteTabela);

        rejeitarButton.setText("Rejeitar");
        rejeitarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rejeitarButtonMouseClicked(evt);
            }
        });

        aceitarButton.setText("Aceitar");
        aceitarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aceitarButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(aceitarButton)
                        .addGap(41, 41, 41)
                        .addComponent(rejeitarButton)
                        .addGap(82, 82, 82)
                        .addComponent(voltarButton)
                        .addGap(0, 68, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltarButton)
                    .addComponent(rejeitarButton)
                    .addComponent(aceitarButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void voltarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarButtonMouseClicked
        Painel_menuUtilizador pInicial = new Painel_menuUtilizador ();
        JFrame.getFrame().AvancarParaPainel(pInicial, this.jPanel1);
        JFrame.getFrame().setSize(600, 400);
        JFrame.getFrame().setLocationRelativeTo(null);
    }//GEN-LAST:event_voltarButtonMouseClicked

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void rejeitarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rejeitarButtonMouseClicked
        
        int row = this.conviteTabela.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(null, "Escolha um utilizador");
            return;
        }
        
        String projeto = (String) this.conviteTabela.getValueAt(row, 0);
        
        Repositorio.getInstance().removeConvite(projeto);
        
        
        Painel_menuUtilizador pInicial = new Painel_menuUtilizador ();
        JFrame.getFrame().AvancarParaPainel(pInicial, this.jPanel1);
        JFrame.getFrame().setSize(600, 400);
        JFrame.getFrame().setLocationRelativeTo(null);
        
    }//GEN-LAST:event_rejeitarButtonMouseClicked

    private void aceitarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceitarButtonMouseClicked
        int row = this.conviteTabela.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(null, "Escolha um utilizador");
            return;
        }
        
        String projeto = (String) this.conviteTabela.getValueAt(row, 0);
        
        Repositorio.getInstance().removeConvite(projeto);
        Repositorio.getInstance().addConvidado(projeto);
                
        
        Painel_menuUtilizador pInicial = new Painel_menuUtilizador ();
        JFrame.getFrame().AvancarParaPainel(pInicial, this.jPanel1);
        JFrame.getFrame().setSize(600, 400);
        JFrame.getFrame().setLocationRelativeTo(null);
    }//GEN-LAST:event_aceitarButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceitarButton;
    private javax.swing.JTable conviteTabela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rejeitarButton;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
